const $ = id => document.getElementById(id);
const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let csrf='',products=[],staff=[];
async function api(route,options={}){const response=await fetch(`/server/api.php?route=${route}`,{credentials:'same-origin',...options});const data=await response.json();if(!response.ok)throw new Error(data.error||'Ошибка запроса');return data;}
const pickupLabel=value=>{const date=new Date(String(value).replace(' ','T')+'Z');return Number.isNaN(date.getTime())?'Время не указано':date.toLocaleString('ru-RU');};
const json=(body)=>({method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(body)});
function showAdmin(logged){$('login-section').hidden=logged;$('dashboard').hidden=!logged;$('logout').hidden=!logged;if(logged){refresh();refreshFeedback();refreshStaff();refreshReport();}}
async function refreshStaff(){try{const data=await api('admin-staff');staff=data.staff;$('staff-list').innerHTML=staff.map(s=>`<p><strong>${esc(s.full_name)}</strong> · ${esc(s.position)} · №${Number(s.id)}</p>`).join('')||'<p>Сотрудники ещё не добавлены.</p>';}catch(err){$('staff-list').textContent=err.message;}}
async function refreshReport(){try{const data=await api('admin-report');$('report-list').innerHTML=data.rows.map(r=>`<p>${esc(r.sale_date)} · заказ ${esc(r.code)} · ${Number(r.item_count)} шт. · ${Number(r.total)} ₽ · ${esc(r.status)} · ${esc(r.responsible_staff||'без сотрудника')}</p>`).join('')||'<p>Заказов для отчёта пока нет.</p>';}catch(err){$('report-list').textContent=err.message;}}
async function refreshFeedback(){try{const data=await api('admin-feedback');$('feedback-list').innerHTML=data.feedback.map(item=>`<article class="feedback-entry"><strong>${esc(item.name)}</strong> · ${esc(item.phone)}<small> · ${esc(item.created_at)}</small><p>${esc(item.message)}</p></article>`).join('')||'<p>Сообщений пока нет.</p>';}catch(err){$('feedback-list').textContent=err.message;}}
async function refresh(){
  try {
    const [orders,catalog,people]=await Promise.all([api('admin-orders'),api('products'),api('admin-staff')]);
    products=catalog.products;staff=people.staff;
    $('orders').innerHTML=orders.orders.map(o=>`<article class="order-card"><h3>Заказ ${esc(o.code)}</h3><p>${esc(o.customer_name)} · ${esc(o.phone)}</p><p>${o.fulfillment==='delivery'?'Доставка':'Самовывоз'}: ${esc(pickupLabel(o.pickup_at))} · ${Number(o.total)} ₽</p>${o.delivery_address?`<p>Адрес: ${esc(o.delivery_address)}</p>`:''}<p>${o.items.map(i=>`${esc(i.name)} × ${Number(i.quantity)}`).join(', ')}</p><label>Статус<select data-order="${Number(o.id)}">${['Новый','Подтверждён','Готов','В пути','Выдан','Отменён'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Ответственный сотрудник<select data-assign="${Number(o.id)}"><option value="">Не назначен</option>${staff.map(s=>`<option value="${Number(s.id)}" ${Number(o.staff_id)===Number(s.id)?'selected':''}>${esc(s.full_name)} · ${esc(s.position)}</option>`).join('')}</select></label></article>`).join('')||'<p>Заказов пока нет.</p>';
    $('admin-products').innerHTML=products.map(p=>`<div class="admin-product"><div><strong>${esc(p.name)}</strong><small>№ ${p.id} · ${Number(p.price)} ₽ · ${Number(p.weight_g)} г · ${Number(p.prep_minutes)} мин · ${Number(p.available)?'в продаже':'скрыт'}</small></div><button type="button" data-edit="${p.id}">Изменить</button></div>`).join('');
  } catch(err){$('orders').textContent=err.message;}
}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;try{const d=await api('login',json({login:f.elements.login.value,password:f.elements.password.value}));csrf=d.csrf;f.reset();$('login-error').textContent='';showAdmin(true);}catch(err){$('login-error').textContent=err.message;}});
$('logout').addEventListener('click',async()=>{try{await api('logout',json({}));const session=await api('session');csrf=session.csrf;showAdmin(false);}catch(err){$('orders').textContent=err.message;}});
$('refresh-orders').addEventListener('click',refresh);
$('refresh-feedback').addEventListener('click',refreshFeedback);
$('orders').addEventListener('change',async e=>{if(!e.target.matches('[data-order]'))return;try{await api('admin-status',json({id:Number(e.target.dataset.order),status:e.target.value}));}catch(err){alert(err.message);refresh();}});
$('admin-products').addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(!b)return;const p=products.find(x=>Number(x.id)===Number(b.dataset.edit));if(!p)return;const f=$('product-form');for(const key of ['id','name','category','price','description','ingredients','allergens','weight_g','prep_minutes'])f.elements[key].value=p[key]??'';f.elements.available.checked=!!Number(p.available);f.scrollIntoView({behavior:'smooth'});});
$('product-reset').addEventListener('click',()=>{$('product-form').reset();$('product-form').elements.id.value='';});
$('product-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const body={id:f.elements.id.value?Number(f.elements.id.value):null,name:f.elements.name.value,category:f.elements.category.value,price:Number(f.elements.price.value),weight_g:Number(f.elements.weight_g.value),prep_minutes:Number(f.elements.prep_minutes.value),description:f.elements.description.value,ingredients:f.elements.ingredients.value,allergens:f.elements.allergens.value,available:f.elements.available.checked};try{const d=await api('admin-product',json(body));$('product-message').textContent=`Товар № ${d.id} сохранён.`;f.reset();f.elements.id.value='';refresh();}catch(err){$('product-message').textContent=err.message;}});
$('orders').addEventListener('change',async e=>{if(!e.target.matches('[data-assign]')||!e.target.value)return;try{await api('admin-assign',json({order_id:Number(e.target.dataset.assign),staff_id:Number(e.target.value)}));refreshReport();}catch(err){alert(err.message);refresh();}});
$('staff-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;try{await api('admin-staff',json({full_name:f.elements.full_name.value,position_id:Number(f.elements.position_id.value),phone:f.elements.phone.value,address:f.elements.address.value,birth_date:f.elements.birth_date.value}));$('staff-message').textContent='Сотрудник добавлен.';f.reset();refreshStaff();refresh();}catch(err){$('staff-message').textContent=err.message;}});
$('refresh-report').addEventListener('click',refreshReport);
$('reset-code-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;try{const result=await api('admin-reset-code',json({phone:f.elements.phone.value}));$('reset-code-message').textContent=`Код: ${result.code}. Передайте его покупателю лично после проверки личности; действует ${result.expires_minutes} минут.`;}catch(err){$('reset-code-message').textContent=err.message;}});
$('image-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const file=f.elements.image.files[0];if(!file||file.size>2*1024*1024){$('image-message').textContent='Выберите файл до 2 МБ.';return;}const body=new FormData(f);try{await api('admin-image',{method:'POST',headers:{'X-CSRF-Token':csrf},body});$('image-message').textContent='Фото загружено.';f.reset();refresh();}catch(err){$('image-message').textContent=err.message;}});
api('session').then(d=>{csrf=d.csrf;showAdmin(d.admin);}).catch(()=>{$('login-error').textContent='Сервер недоступен.';});
